[tool.poetry]
name = "testasyncio"
version = "0.1.0"
description = ""
authors = ["Adam Beret Manczuk <beret@hipisi.org.pl>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
